version: '3'

networks:
  mt-network:
    driver: bridge

services:
  mt-proxy:
    image: nginx:alpine
    container_name: mt-proxy
    ports:
      - "9100:4000"
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/conf.d:/etc/nginx/conf.d
    networks:
      mt-network:
        aliases:
          - proxy
  
  mt-node-exporter:
    image: prom/node-exporter:latest
    container_name: mt-node-exporter
    ports:
      - "9100"
    networks:
      mt-network:
        aliases:
          - node-exporter

  mt-cadvisor:
    image: gcr.io/cadvisor/cadvisor
    container_name: mt-cadvisor
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    ports:
      - "8080"
    networks:
      mt-network:
        aliases:
          - cadvisor
    restart: always
    deploy:
      mode: global
